libfbi: SetA< BoxType, TIndices > Class Template Reference
SetA< BoxType, TIndices > Class Template Reference
A class to find intersections between cartesian products of arbitrarily-typed intervals.
Classes
class HybridScanner
Find intersections between boxes by recursing through virtual segment trees.
struct HybridScanner< PointsContainQueries, SetA< BoxType, TIndices...>::LASTDIM >
class IntersectionTester
Check in if two intervals intersect by comparing in all dimensions till it's either false or all tests evaluated to true.
class KeyCreator
Handle the creation of keys by using given functors. As we have to handle variable indices, both from SetA and SetB, we have to add another template class to use different std::size_t parameter packs.
class KeyPrinter
For Debug reasons, print all dimensions of a given key via cout.
struct KeyPrinter< N, N >
class lessHead
This Functor compares the lower endpoints of two key_type objects in a given dimension.
class lessTail
This Functor compares the upper endpoints of two key_type objects in a given dimension.
class OneWayScanner
A scanner to find one type of intersection between two sets of intervals by looking at one of them as a set of points.
class SetB
Subclass, when the type of the query objects differs from the type of the data objects, we need an additional layer of template specialization.
class State
Holding various information like the random generator state, some specific addresses of data and dimensional limits.
Public Types
typedef uint32_t IntType
typedef std::vector< std::set
< IntType > > ResultType
Static Public Member Functions
template<class BoxContainer , typename = typename std::enable_if< std::is_same<typename BoxContainer::value_type, value_type>::value> ::type, typename IntervalFunctor , typename... QueryFunctors>
static ResultType intersect (const BoxContainer &dataContainer, const IntervalFunctor &ifunctor, const QueryFunctors &...qfunctors)
template<class BoxContainer , typename = typename std::enable_if< std::is_same<typename BoxContainer::value_type, value_type>::value> ::type, typename IntervalFunctor , typename... QueryFunctors>
static ResultType thetaIntersect (const std::size_t cutoff, const BoxContainer &dataContainer, const IntervalFunctor &ifunctor, const QueryFunctors &...qfunctors)
Private Types
enum { LASTDIM }
enum { TINDICESCORRECT, value }
typedef std::tuple< typename
std::tuple_element< TIndices,
typename Traits< value_type >
::dim_type >
::type::second_type... > comp_type
typedef std::tuple< typename
std::tuple_element< TIndices,
typename Traits< value_type >
::key_type >::type... > key_type
typedef SetA< BoxType, TIndices...> SETA
typedef BoxType value_type
Private Member Functions
SetA ()
static_assert (TINDICESCORRECT,"Please check your SetA-Indices again, the \ Traits<BoxType>::key_type \ does not have enough dimensions to use your indices")
static_assert (sizeof...(TIndices) > 0,"Please specify at least one index for the dimensions")
Static Private Member Functions
static const std::vector
< const key_type * > createPtrVector (const std::vector< key_type > &container)
template<std::size_t Dim>
static const
std::tuple_element< Dim,
key_type >::type::first_type getApproxMedian (const std::vector< const key_type * > &container, const std::size_t height, State &state, const typename std::tuple_element< Dim, comp_type >::type &less)
template<std::size_t Dim>
static const
std::tuple_element< Dim,
comp_type >::type getCompareFunctor ()
template<std::size_t Dim>
static std::tuple_element< Dim,
key_type >::type::first_type getHead (const key_type *key)
template<std::size_t Dim>
static std::tuple_element< Dim,
key_type >::type::first_type getHead (const key_type &key)
template<std::size_t Dim>
static std::tuple_element< Dim,
key_type >::type getKey (const key_type *key)
template<std::size_t Dim>
static std::tuple_element< Dim,
key_type >::type getKey (const key_type &key)
template<std::size_t Dim>
static std::tuple_element< Dim,
key_type >::type::first_type getTail (const key_type *key)
template<std::size_t Dim>
static std::tuple_element< Dim,
key_type >::type::first_type getTail (const key_type &key)
static const std::size_t heuristicHeight (std::size_t numElements)
template<typename T , typename Comp >
static const T & medianOfThree (const T &t1, const T &t2, const T &t3, const Comp &less)
template<std::size_t Dim>
static void sortContainerHead (std::vector< const key_type * > &container)
template<std::size_t Dim>
static void sortContainerTail (std::vector< const key_type * > &container)
Detailed Description
template<typename BoxType, std::size_t... TIndices>
class fbi::SetA< BoxType, TIndices >
A class to find intersections between cartesian products of arbitrarily-typed intervals.
Based on "Fast Software for Box Intersections", by Afra Zomorodian, Herbert Edelsbrunner,
Template Parameters:
BoxType The objects we're looking at, Traits<BoxType> has to available.
Note:
To work correctly on the given types, the templated Traits class has to be specialized for the given BoxType (and QBoxType, if needed).
See also:
Traits
Template Parameters:
TIndices Two boxes shall intersect if they do in these dimensions, given as a parameter pack of std::size_t.
Note:
The user has to specify at least one index to work on, empty TIndices won't return any results.
Definition at line 77 of file fbi.h.
Member Typedef Documentation
typedef std::tuple< typename std::tuple_element< TIndices, typename Traits<value_type>::dim_type >::type::second_type ... > comp_type [private]
As every dimension can have a different type, the appropriate comparison-operator has to be known during compile-time.
See also:
fbi::Traits
Definition at line 143 of file fbi.h.
typedef uint32_t IntType
Every intersection between two elements will be represented by their corresponding index in the container holding BoxType, to save memory we decided to artificially limit the amount of elements which allows us to use 32Bit integers instead of 64Bit.
Definition at line 154 of file fbi.h.
typedef std::tuple< typename std::tuple_element< TIndices, typename Traits<value_type>::key_type >::type ... > key_type [private]
The key is represented by a pair of values for each dimension that should be considered for intersection tests, these pairs are wrapped in a std::tuple for easy access via std::get.
See also:
fbi::Traits
Note:
This key_type is a subset of the original key_type, depending on the indices we're using.
Definition at line 129 of file fbi.h.
typedef std::vector<std::set<IntType> > ResultType
The intersections will be returned as a adjacency list, to prevent parallel edges we're using a set for the inner dimension.
Definition at line 161 of file fbi.h.
typedef SetA<BoxType, TIndices...> SETA [private]
Small self-referencing typedef
Definition at line 87 of file fbi.h.
typedef BoxType value_type [private]
Short typedef to offer the STL value_type identifier for this tree.
Definition at line 93 of file fbi.h.
Member Enumeration Documentation
anonymous enum [private]
A compile-time constant to mark recursion tails.
Definition at line 90 of file fbi.h.
anonymous enum [private]
enum to do compile-time indices checks and better error output
Enumerator:
TINDICESCORRECT
TINDICESCORRECT is 1 when all TIndices can be used to access a dimension the key_type, otherwise it's 0
Definition at line 96 of file fbi.h.
Constructor & Destructor Documentation
SetA () [private]
Keep ctor private to leave it as a class - we don't want a tree object.
Member Function Documentation
static const std::vector<const key_type *> createPtrVector (const std::vector< key_type > & container) [static, private]
Create a vector with pointers to our interval data to save memory.
Parameters:
container A STL container holding key_type objects, has to have a const_iterator. As our scanfunctions have to pass and copy containers of intervals, using a pointer based approach was deemed faster and safer as we won't modify the actual data.
See also:
KeyCreator::getVector()
Note:
Don't move/insert into the intervalContainer afterwards, as it will invalidate all pointers.
Definition at line 489 of file fbi.h.
References vector< _Tp, _Alloc >::begin(), vector< _Tp, _Alloc >::end(), and vector< _Tp, _Alloc >::size().
Referenced by SetB< QBoxType, QIndices >::intersect(), and SetB< QBoxType, QIndices >::thetaIntersect().
static const std::tuple_element<Dim, key_type>::type::first_type getApproxMedian (const std::vector< const key_type * > & container, const std::size_t height, State & state, const typename std::tuple_element< Dim, comp_type >::type & less) [static, private]
Calculate an approximate median by using the median-of-three method on a ternary tree of given height.
Template Parameters:
Dim Get the median of a vector of values in the given dimension.
See also:
heuristicHeight()
Parameters:
[in] container The vector of values we're interested in
[in] height The depth of the triadic tree we're resolving to get a median
[in,out] state The object holding the random number generator
[in] less The comparison operator so that we can compare in a specific dimension
Definition at line 447 of file fbi.h.
References SetA< BoxType, TIndices >::medianOfThree(), State::randInt(), and vector< _Tp, _Alloc >::size().
static const std::tuple_element<Dim, comp_type >::type getCompareFunctor () [static, private]
Comfort function to get the comparison functor in the correct dimension
Definition at line 569 of file fbi.h.
static std::tuple_element<Dim,key_type>::type::first_type getHead (const key_type * key) [static, private]
Comfort function to get the lower endpoint in the correct dimension
Parameters:
[in] key The box object
Definition at line 541 of file fbi.h.
static std::tuple_element<Dim,key_type>::type::first_type getHead (const key_type & key) [static, private]
Comfort function to get the lower endpoint in the correct dimension
Parameters:
[in] key The box object
Definition at line 532 of file fbi.h.
static std::tuple_element<Dim,key_type>::type getKey (const key_type * key) [static, private]
Comfort function to get the interval in the correct dimension
Parameters:
[in] key The box object
Definition at line 522 of file fbi.h.
static std::tuple_element<Dim,key_type>::type getKey (const key_type & key) [static, private]
Some easy ways to get the correct interval / endpoints in a given dimension
Template Parameters:
Dim dimension to work on. Comfort function to get the interval in the correct dimension
Parameters:
[in] key The box object
Definition at line 513 of file fbi.h.
static std::tuple_element<Dim,key_type>::type::first_type getTail (const key_type * key) [static, private]
Comfort function to get the upper endpoint in the correct dimension
Parameters:
[in] key The box object
Definition at line 561 of file fbi.h.
static std::tuple_element<Dim,key_type>::type::first_type getTail (const key_type & key) [static, private]
Comfort function to get the upper endpoint in the correct dimension
Parameters:
[in] key The box object
Definition at line 550 of file fbi.h.
static const std::size_t heuristicHeight (std::size_t numElements) [static, private]
Calculate the depth of the approximate median tree, as some constants here have to be found by experiment.
Parameters:
[in] numElements the height of the ternary tree shall be dependent on the number of elements
See also:
getApproxMedian()
Definition at line 635 of file fbi.h.
References log().
Referenced by HybridScanner< PointsContainQueries, Dim >::scan().
static ResultType intersect (const BoxContainer & dataContainer, const IntervalFunctor & ifunctor, const QueryFunctors &... qfunctors) [static]
Create two sets of keys by intersecting two sets of functors on a given dataContainer, and check if there are intersections between these keys in the dimensions the tree was initialized with.
In the general case, we would like to have two different types of boxes, which, given functors, produce the same key_type. As their keys are then equal and also a representation of hyperrectangles (cartesian products of intervals), it is possible to test for intersections between them.
Parameters:
[in] dataContainer A container with a const_iterator, it has to hold the same type as the one the tree was instantiated with. Both key sets will be extracted by using functors on every value in this container.
[in] ifunctor This has to be either a class with a public
get<Dim>(const BoxType &) const;
method or a std::vector holding that kind of class, if multiple interval objects per box should be made. The tree will create the keys by using the functor to extract the indexed dimensions from the BoxType.
[in] qfunctors Like ifunctor, these functors will each create a different key, they can also be of type std::vector<functor>, for every object in each vector one query will be created per box in dataContainer.
Returns:
We'll return a std::vector<std::set<IntType> >, as parallel edges are possible but not desired for the end result. An edge (pair of two boxes), consisting of 2 IntType values a and b -which refer to the indices of these boxes in dataContainer- is represented by b being in the set of tails belonging to the head a, as there are |dataContainer| sets in the result. Note that every edge is inserted twice as intersection is reflective and the result an undirected graph.
See also:
SetB::intersect
Definition at line 353 of file fbi.h.
References SetB< QBoxType, QIndices >::intersect().
static const T& medianOfThree (const T & t1, const T & t2, const T & t3, const Comp & less) [static, private]
Calculate the median of three values, comparison functor has to be provided.
Template Parameters:
T type of compared values
Comp comparison functor
Parameters:
[in] t1 first object to compare
[in] t2 second object to compare
[in] t3 third object to compare
[in] less comparison object
See also:
getApproxMedian()
Definition at line 608 of file fbi.h.
Referenced by SetA< BoxType, TIndices >::getApproxMedian().
static void sortContainerHead (std::vector< const key_type * > & container) [static, private]
Sort a container of pointers to key_type objects, compare their lower endpoints in the specified dimension
Parameters:
[in] container The container to sort.
Definition at line 580 of file fbi.h.
References vector< _Tp, _Alloc >::begin(), vector< _Tp, _Alloc >::end(), and sort().
static void sortContainerTail (std::vector< const key_type * > & container) [static, private]
Sort a container of pointers to key_type objects, compare their upper endpoints in the specified dimension
Parameters:
[in] container The container to sort
Definition at line 591 of file fbi.h.
References vector< _Tp, _Alloc >::begin(), vector< _Tp, _Alloc >::end(), and sort().
static_assert (TINDICESCORRECT , "Please check your SetA< BoxType, TIndices >-Indices again, the\Traits< BoxType >::key_type\does not have enough dimensions to use your indices") [private]
Throw a compile error when the indices aren't correct.
static_assert (sizeof... TIndices, 0 , "Please specify at least one index for the dimensions") [private]
Empty TIndices shouldn't work
Referenced by KeyCreator< KeyCreatorIndices >::getVector(), SetB< QBoxType, QIndices >::intersect(), and SetB< QBoxType, QIndices >::thetaIntersect().
static ResultType thetaIntersect (const std::size_t cutoff, const BoxContainer & dataContainer, const IntervalFunctor & ifunctor, const QueryFunctors &... qfunctors) [static]
Create two sets of keys by intersecting two sets of functors on a given dataContainer, and check if there are intersections between these keys in the dimensions the tree was initialized with.
In the general case, we would like to have two different types of boxes, which, given functors, produce the same key_type. As their keys are then equal and also a representation of hyperrectangles (cartesian products of intervals), it is possible to test for intersections between them.
Parameters:
[in] cutoff If one of the containers has less elements than cutoff, switch to brute-force algorithm.
[in] dataContainer A container with a const_iterator, it has to hold the same type as the one the tree was instantiated with. Both key sets will be extracted by using functors on every value in this container.
[in] ifunctor This has to be either a class with a public
get<Dim>(const BoxType &) const;
method or a std::vector holding that kind of class, if multiple interval objects per box should be made. The tree will create the keys by using the functor to extract the indexed dimensions from the BoxType.
[in] qfunctors Like ifunctor, these functors will each create a different key, they can also be of type std::vector<functor>, for every object in each vector one query will be created per box in dataContainer.
Returns:
We'll return a std::vector<std::set<IntType> >, as parallel edges are possible but not desired for the end result. An edge (pair of two boxes), consisting of 2 IntType values a and b -which refer to the indices of these boxes in dataContainer- is represented by b being in the set of tails belonging to the head a (and vice versa), as there are |dataContainer| sets in the result. Note that every edge is inserted twice as intersection is reflective and the result an undirected graph.
See also:
SetB::intersect
Definition at line 413 of file fbi.h.
References SetB< QBoxType, QIndices >::thetaIntersect().
The documentation for this class was generated from the following file:
fbi.h