tree: State Class Reference
State Class Reference
Holding various information like the random generator state, some specific addresses of data and dimensional limits.
Public Member Functions
State (const key_type &limits, const std::size_t numMod, const key_type *queryVectorPtr, const key_type *dataVectorPtr, const std::size_t offset, const std::size_t cutoffSize=250, std::size_t(*heightCalculator)(const std::size_t)=&(SETA::State::defaultHeightCalculator_))
std::size_t calculate (bool isQueryVectorPtr, const key_type *objectPtr) const
std::size_t getCutoff () const
const key_type & getLimits () const
std::size_t heuristicHeight (const std::size_t n) const
std::size_t randInt (std::size_t lowerBound, std::size_t upperBound)
Private Types
typedef
std::uniform_int_distribution
< std::size_t > Distribution
Static Private Member Functions
static std::size_t defaultHeightCalculator_ (const std::size_t n)
Private Attributes
const std::size_t cutoffSize_
const key_type * dataVectorPtrToFirstElement_
std::size_t(*const heightCalculator_)(const std::size_t)
const key_type limits_
const std::size_t numModifications_
const std::size_t offset_
const key_type * queryVectorPtrToFirstElement_
std::mt19937 rSeedEngine_
Detailed Description
template<typename BoxType, std::size_t... TIndices>
class fbi::SetA< BoxType, TIndices >::State
Holding various information like the random generator state, some specific addresses of data and dimensional limits.
Definition at line 1034 of file fbi.h.
Member Typedef Documentation
typedef std::uniform_int_distribution<std::size_t> Distribution [private]
We need a uniform distribution
Definition at line 1081 of file fbi.h.
Constructor & Destructor Documentation
State (const key_type & limits, const std::size_t numMod, const key_type * queryVectorPtr, const key_type * dataVectorPtr, const std::size_t offset, const std::size_t cutoffSize = 250, std::size_t(*)(const std::size_t) heightCalculator = &(SETA::State::defaultHeightCalculator_))
Constructor of the state we'll pass through most of the algorithm.
Parameters:
limits The bounds in every dimension of the key, they're needed to have values which are smaller/higher than all possible values, see HybridScanner
numMod The number of queries which are assigned to each input data: As we want to calculate the true indices of the queries from their pointers and several queries can belong to the same original object, we have to use this.
queryVectorPtr Pointer to the first object in the queryVector, needed to calculate the offset.
dataVectorPtr Pointer to the first object in the dataVector, needed to calculate the offset.
offset Needed to correctly calculate the indices, equal to sizeof(SetA)
cutoffSize Minimum amount of query and data objects to handle in HybridScanner, if one of them falls below that value, switch to OneWayScanner.
heightCalculator Function pointer to a heuristic which returns the height to use in getApproxMedian.
Definition at line 1120 of file fbi.h.
Member Function Documentation
std::size_t calculate (bool isQueryVectorPtr, const key_type * objectPtr) const
As we pass pointers around during our algorithm, it is necessary to find the corresponding index of the objects when writing pairs as results. To do this, we first save the pointer to the respective first object, using our knowledge of the memory representation a simple pointer subtraction yields the original index.
Parameters:
[in] isQueryVectorPtr We have to keep track if a pointer refers to a box in the first or second input set as that changes its index.
[in] objectPtr a pointer to a key, can be either generated from the first or second type of boxes.
Definition at line 1154 of file fbi.h.
Referenced by OneWayScanner< PointsContainQueries, Dim >::scan().
static std::size_t defaultHeightCalculator_ (const std::size_t n) [static, private]
A reasonably good method to calculate the height of an approximate median ternary tree
Parameters:
[in] n Number of elements to get the median from
Definition at line 1043 of file fbi.h.
References log10(), and max().
std::size_t getCutoff () const
Getter
Definition at line 1190 of file fbi.h.
Referenced by HybridScanner< PointsContainQueries, Dim >::scan().
const key_type& getLimits () const
Getter
Definition at line 1181 of file fbi.h.
Referenced by SetB< QBoxType, QIndices >::intersect(), and SetB< QBoxType, QIndices >::thetaIntersect().
std::size_t heuristicHeight (const std::size_t n) const
Return a good height for the ternary median tree
Parameters:
n Number of elements
Definition at line 1185 of file fbi.h.
Referenced by HybridScanner< PointsContainQueries, Dim >::scan().
std::size_t randInt (std::size_t lowerBound, std::size_t upperBound)
In getApproxMedian we have to pick a random object, this returns a random integer between its two inputs.
Parameters:
[in] lowerBound The returned integer will be greater or equal to this
[in] upperBound The returned integer will be lesser than this
Definition at line 1175 of file fbi.h.
Referenced by SetA< BoxType, TIndices >::getApproxMedian().
Member Data Documentation
const std::size_t cutoffSize_ [private]
Also known as theta, the margin to switch to brute-force
Definition at line 1090 of file fbi.h.
const key_type* dataVectorPtrToFirstElement_ [private]
Pointer to the first element in the interval-(data-)Vector, created for the scan, this pointer is needed to recalculate the index of a specific element as we're passing pointers to the vector containing the dataIntervals.
Definition at line 1075 of file fbi.h.
std::size_t(* const heightCalculator_)(const std::size_t) [private]
Function pointer to a height calculator
const key_type limits_ [private]
For every dimension, upper and lower bounds have to be known, which will be larger or smaller than all possible values.
Definition at line 1055 of file fbi.h.
const std::size_t numModifications_ [private]
As it is possible to create several keys per box, we have to remember the number so index-calculations can be done
Definition at line 1062 of file fbi.h.
const std::size_t offset_ [private]
As our second set of objects continues the numbering scheme of the first, we have to add an offset to the indices.
Definition at line 1086 of file fbi.h.
const key_type* queryVectorPtrToFirstElement_ [private]
Pointer to the first element in the points-(query-)Vector, created for the scan, This pointer is needed to recalculate the index of a specific element as we're passing pointers to the vector containing the queryIntervals.
Definition at line 1069 of file fbi.h.
std::mt19937 rSeedEngine_ [private]
Random seed engine, has to be non-const as using the engine changes it.
Definition at line 1079 of file fbi.h.
The documentation for this class was generated from the following file:
fbi.h