tree: HybridScanner< PointsContainQueries, Dim > Class Template Reference
HybridScanner< PointsContainQueries, Dim > Class Template Reference
Find intersections between boxes by recursing through virtual segment trees.
Static Public Member Functions
static void scan (std::vector< const key_type * > &pointsPtrVector, std::vector< const key_type * > &intervalsPtrVector, const typename std::tuple_element< Dim, key_type >::type::first_type &lowerBound, const typename std::tuple_element< Dim, key_type >::type::first_type &upperBound, State &state, ResultType &resultVector)
Detailed Description
template<typename BoxType, std::size_t... TIndices>
template<bool PointsContainQueries, std::size_t Dim>
class fbi::SetA< BoxType, TIndices >::HybridScanner< PointsContainQueries, Dim >
Find intersections between boxes by recursing through virtual segment trees.
We're interested in finding the intersections between two bipartite sets. Similar to other divide & conquer algorithms, we will recursively divide the problem into smaller pieces, till we only have to check for intersections between two small subsets with a brute-force algorithm. To find all intersections, we have to alternate between looking at the intervals as points and as intervals, which means that every instance of HybridScanner has to spawn two HybridScanners for the next dimension with alternating inputs.
Note:
Like Quicksort, we would like to use the median to divide our sets into equal parts. As an exact median calculation would be too tiresome, we used a heuristic which is a generalized version of the standard medianOfThree method to find a good approximation.
See also:
ref getApproxMedian
ref OneWayScanner
Definition at line 1248 of file fbi.h.
Member Function Documentation
static void scan (std::vector< const key_type * > & pointsPtrVector, std::vector< const key_type * > & intervalsPtrVector, const typename std::tuple_element< Dim, key_type >::type::first_type & lowerBound, const typename std::tuple_element< Dim, key_type >::type::first_type & upperBound, State & state, ResultType & resultVector) [static]
Find intersections by solving the 1-dimensional problems of overlapping intervals.
This is the main recursion function, it is a divide & conquer algorithm, quite similar to quicksort. By creating the nodes of a virtual segment tree in post-order, we don't have to look at the whole tree at once (saving memory). In 1 iteration, we can split the intervalset in 3 separate sets:
Two of them represent the child-nodes of the virtual segment tree we're working on (we have to further seperate in the current dimension).
The third one is a set of solutions in the current dimension -> we can solve the problem in the next dimension.
Parameters:
[in] pointsPtrVector As we're looking at two subsets of intervals, this is the one representing the points.
[in] intervalsPtrVector These are the intervals, for this call.
[in] lowerBound As a recursion invariant, all points represented by pointsPtrVector are inbetween the two bounds (check recursion), which is why all intervals spanning across these bounds are intersecting with the points (in the current dimension).
[in] upperBound see lowerBound
[in,out] state Contains a rng, can be used to track the recursion and is able to calculate the indices.
[in,out] resultVector We pass the resultVector around to add to it in OneWayScan
Note:
The resultVector is only modified in OneWayScanner so the algorithm has to end there. We're switching to the OneWayScanner, which is more of a brute-force approach, when either of the two cutoff values is met:
Only one dimension is left
Either set is small enough that a match in one dimension will probably lead to a match in the others.
Definition at line 1285 of file fbi.h.
References vector< _Tp, _Alloc >::begin(), vector< _Tp, _Alloc >::clear(), vector< _Tp, _Alloc >::end(), State::getCutoff(), State::heuristicHeight(), SetA< BoxType, TIndices >::heuristicHeight(), vector< _Tp, _Alloc >::push_back(), vector< _Tp, _Alloc >::size(), and swap().
The documentation for this class was generated from the following file:
fbi.h