libfbi: FunctorChecker Struct Reference
FunctorChecker Struct Reference
Static Public Member Functions
template<class Functor >
static std::size_t count (const std::vector< Functor > &functor)
template<class Functor , class... Functors>
static std::size_t count (const std::vector< Functor > &functor, const Functors &...functors)
template<class Functor >
static std::size_t count (const Functor &functor)
template<class Functor , class... Functors>
static std::size_t count (const Functor &functor, const Functors &...functors)
Detailed Description
Templated helper class, returns the number of functors passed. As we should be able to pass multiple types of functors and even multiple objects per type, we need to calculate how many functors there are. This is needed to calculate the original indices of the boxes from given pointers, as only they are passed around - the re-identification is made by pointer-arithmetic.
Definition at line 233 of file tuplegenerator.h.
Member Function Documentation
static std::size_t count (const std::vector< Functor > & functor) [static]
Specialized case, if only one functor-type is left and that one is a vector, count every instantiated object of that typein the container.
Parameters:
functor A single functor or a vector of functors of the same type, having a
get<Dim>(const BoxType &) const;
method
Definition at line 275 of file tuplegenerator.h.
References vector< _Tp, _Alloc >::size().
static std::size_t count (const std::vector< Functor > & functor, const Functors &... functors) [static]
Specialized function call, if the passed object is a std::vector of functors, count all of them as we will create one object per vector-size.
Parameters:
functor A single functor or a vector of functors of the same type, having a
get<Dim>(const BoxType &) const;
method
functors More functors
Definition at line 264 of file tuplegenerator.h.
References count(), and vector< _Tp, _Alloc >::size().
static std::size_t count (const Functor & functor) [static]
If there is only a single functor left, add 1
Parameters:
functor A single functor, having a
get<Dim>(const BoxType &) const;
method
Definition at line 251 of file tuplegenerator.h.
static std::size_t count (const Functor & functor, const Functors &... functors) [static]
If the current head is a single functor-object, add 1
Parameters:
functor A single functor, having a
get<Dim>(const BoxType &) const;
method
functors Other functors, see functor
Definition at line 242 of file tuplegenerator.h.
References count().
The documentation for this struct was generated from the following file:
tuplegenerator.h