libfbi: SetB< QBoxType, QIndices > Class Template Reference
SetB< QBoxType, QIndices > Class Template Reference
Subclass, when the type of the query objects differs from the type of the data objects, we need an additional layer of template specialization.
Static Public Member Functions
template<class BoxContainer , typename = typename std::enable_if<std::is_same<typename BoxContainer::value_type, value_type>::value>::type, class QContainer , typename = typename std::enable_if<std::is_same<typename QContainer::value_type, qvalue_type>::value>::type, typename IntervalFunctor , typename... QueryFunctors>
static ResultType intersect (const BoxContainer &dataContainer, const IntervalFunctor &ifunctor, const QContainer &qdataContainer, const QueryFunctors &...qfunctors)
template<class BoxContainer , typename = typename std::enable_if<std::is_same<typename BoxContainer::value_type, value_type>::value>::type, class QContainer , typename = typename std::enable_if<std::is_same<typename QContainer::value_type, qvalue_type>::value>::type, typename IntervalFunctor , typename... QueryFunctors>
static ResultType thetaIntersect (const size_t cutoff, const BoxContainer &dataContainer, const IntervalFunctor &ifunctor, const QContainer &qdataContainer, const QueryFunctors &...qfunctors)
Private Types
typedef std::tuple< typename
std::tuple_element< QIndices,
typename Traits< qvalue_type >
::dim_type >
::type::second_type... > qcomp_type
typedef std::tuple< typename
std::tuple_element< QIndices,
typename Traits< qvalue_type >
::key_type >::type... > qkey_type
typedef QBoxType qvalue_type
Private Member Functions
static_assert (std::is_same< comp_type, qcomp_type >::value,"CompTypes don't match")
static_assert (std::is_same< key_type, qkey_type >::value,"Keytypes don't match")
static_assert (sizeof...(QIndices)==sizeof...(TIndices),"Your number of query-dimensions doesn't match your initial indices")
Detailed Description
template<typename BoxType, std::size_t... TIndices>
template<typename QBoxType, std::size_t... QIndices>
class fbi::SetA< BoxType, TIndices >::SetB< QBoxType, QIndices >
Subclass, when the type of the query objects differs from the type of the data objects, we need an additional layer of template specialization.
Definition at line 648 of file fbi.h.
Member Typedef Documentation
typedef std::tuple< typename std::tuple_element<QIndices, typename Traits<qvalue_type>::dim_type >::type::second_type ... > qcomp_type [private]
As every dimension can have a different type, the appropriate comparison-operator has to be known during compile-time.
See also:
fbi::Traits
Definition at line 683 of file fbi.h.
typedef std::tuple< typename std::tuple_element< QIndices, typename Traits<qvalue_type>::key_type >::type ... > qkey_type [private]
The key is represented by a pair of values for each dimension that should be considered for intersection tests, these pairs are wrapped in a std::tuple for easy access via std::get.
See also:
fbi::Traits
Note:
This key_type is a subset of the original key_type, depending on the indices we're using.
Definition at line 668 of file fbi.h.
typedef QBoxType qvalue_type [private]
A comfort typedef to refer to the type of the input boxes
Definition at line 655 of file fbi.h.
Member Function Documentation
static ResultType intersect (const BoxContainer & dataContainer, const IntervalFunctor & ifunctor, const QContainer & qdataContainer, const QueryFunctors &... qfunctors) [static]
The public interface for the user to start the algorithm.
This function initializes the keys (consisting of intervals in several dimensions) of the intervalSet and the querySet, along with pointers to pass them to separation algorithms. State::calculate has to be used to recalculate the original indices from the pointers.
Parameters:
[in] dataContainer STL Container providing a forward iterator and holding a value_type.
[in] ifunctor This has to be either a class with a public
get<Dim>(const BoxType &) const;
method or a std::vector holding that kind of class, if multiple interval objects per box should be made. The tree will create the keys by using the functor to extract the indexed dimensions from the BoxType. They will work on every object in dataContainer.
[in] qdataContainer STL Container providing a forward iterator and holding a qvalue_type.
[in] qfunctors Like ifunctor, these functors will each create a different key, they can also be of type std::vector<functor>, for every object in each vector one query will be created per object in qdataContainer. (|qfunctors.size()| * |qdataContainer| for every qfunctors type)
Returns:
We'll return a std::vector<std::set<IntType> >, as parallel edges are possible but not desired for the end result. Note that in the bipartite case, the boxes in dataContainer will be indexed from 0 upto |dataContainer|-1, whereas the ones in qdataContainer are identified by |dataContainer|..|dataContainer + qdataContainer|-1. An edge (pair of two boxes), consisting of 2 IntType values a and b, is represented by b being in the set of tails belonging to the head a (and vice versa) as there are |dataContainer + qdataContainer|-1 sets in the result. Note that every edge is inserted twice as intersection is reflective and the result an undirected graph.
Definition at line 738 of file fbi.h.
References count(), SetA< BoxType, TIndices >::createPtrVector(), State::getLimits(), make_tuple(), and SetA< BoxType, TIndices >::static_assert().
Referenced by SetA< BoxType, TIndices >::intersect().
static_assert (std::is_same< comp_type, qcomp_type >::value , "CompTypes don't match") [private]
Ensure that the comparison operators are equal
static_assert (std::is_same< key_type, qkey_type >::value , "Keytypes don't match") [private]
Ensure that the key_types are equal
static_assert (sizeof... QIndices = =sizeof...(TIndices), "Your number of query-dimensions doesn't match your initial indices") [private]
Ensure that the number of querydimensions for both sets are equal
static ResultType thetaIntersect (const size_t cutoff, const BoxContainer & dataContainer, const IntervalFunctor & ifunctor, const QContainer & qdataContainer, const QueryFunctors &... qfunctors) [static]
The public interface for the user to start the algorithm.
This function initializes the keys (consisting of intervals in several dimensions) of the intervalSet and the querySet, along with pointers to pass them to separation algorithms. State::calculate has to be used to recalculate the original indices from the pointers.
Parameters:
[in] cutoff The theta cutoff value for switching into OneWayScan
[in] dataContainer STL Container providing a forward iterator and holding a value_type.
[in] ifunctor This has to be either a class with a public
get<Dim>(const BoxType &) const;
method or a std::vector holding that kind of class, if multiple interval objects per box should be made. The tree will create the keys by using the functor to extract the indexed dimensions from the BoxType. They will work on every object in dataContainer.
[in] qdataContainer STL Container providing a forward iterator and holding a qvalue_type.
[in] qfunctors Like ifunctor, these functors will each create a different key, they can also be of type std::vector<functor>, for every object in each vector one query will be created per object in qdataContainer. (|qfunctors.size()| * |qdataContainer| for every qfunctors type) as parallel edges are possible but not desired for the end result. Note that in the bipartite case, the boxes in dataContainer will be indexed from 0 upto |dataContainer|-1, whereas the ones in qdataContainer are identified by |dataContainer|..|dataContainer + qdataContainer|-1. An edge (pair of two boxes), consisting of 2 IntType values a and b, is represented by b being in the set of tails belonging to the head a (and vice versa) as there are |dataContainer + qdataContainer|-1 sets in the result. Note that every edge is inserted twice as intersection is reflective and the result an undirected graph.
Definition at line 854 of file fbi.h.
References count(), SetA< BoxType, TIndices >::createPtrVector(), State::getLimits(), make_tuple(), and SetA< BoxType, TIndices >::static_assert().
Referenced by SetA< BoxType, TIndices >::thetaIntersect().
The documentation for this class was generated from the following file:
fbi.h