tree: KeyCreator< KeyCreatorIndices > Class Template Reference
KeyCreator< KeyCreatorIndices > Class Template Reference
Handle the creation of keys by using given functors. As we have to handle indices which aren't known at the time of the tree instantiation, we have to add another template class to use different size_t parameter packs.
Static Public Member Functions
template<typename T , typename Functor >
static const key_type createKey (const T &val, const Functor &functor)
template<typename T , typename Functor , typename... Functors>
static void createKeys (typename std::vector< key_type >::iterator &intervalIt, const T &dataValue, const Functor &functor, const std::vector< Functors > &...functors)
template<typename T , typename Functor >
static void createKeys (typename std::vector< key_type >::iterator &intervalIt, const T &dataValue, const std::vector< Functor > &functor)
template<typename T , typename Functor , typename... Functors>
static void createKeys (typename std::vector< key_type >::iterator &intervalIt, const T &dataValue, const Functor &functor, const Functors &...functors)
template<typename T , typename Functor >
static void createKeys (typename std::vector< key_type >::iterator &intervalIt, const T &dataValue, const Functor &functor)
template<class Container , class... Functors>
static std::vector< key_type > getVector (const Container &container, const Functors &...functors)
Detailed Description
template<typename BoxType, size_t... TIndices>
template<size_t... KeyCreatorIndices>
class fbi::SetA< BoxType, TIndices >::KeyCreator< KeyCreatorIndices >
Handle the creation of keys by using given functors. As we have to handle indices which aren't known at the time of the tree instantiation, we have to add another template class to use different size_t parameter packs.
Definition at line 752 of file fbi.h.
Member Function Documentation
static const key_type createKey (const T & val, const Functor & functor) [static]
Create a key_type object (which is a tuple of pairs) by calling the getInterval function of the box object in all relevant dimensions.
See also:
ScanFunctions
Definition at line 892 of file fbi.h.
References std::make_tuple().
static void createKeys (typename std::vector< key_type >::iterator & intervalIt, const T & dataValue, const Functor & functor, const std::vector< Functors > &... functors) [static]
Use functors on a given value_type object to create a key for every functor.
Parameters:
intervalIt Iterator to a container which will hold the different keys.
dataValue That's the box representing the class we're working on.
functor Functor which provides a std::pair<...> get<size_t>(value_type) member function
functors Other functors which will be used recursively.
See also:
createKeyType()
Definition at line 870 of file fbi.h.
static void createKeys (typename std::vector< key_type >::iterator & intervalIt, const T & dataValue, const std::vector< Functor > & functor) [static]
This is the tail of a recursive call which uses different functors to produce several queries.
Parameters:
intervalIt Iterator to a container which will hold the different keys.
dataValue That's the box representing the class we're working on.
functor Functor which provides a std::pair<...> get<size_t>(value_type) member function
See also:
createKeyType()
Definition at line 846 of file fbi.h.
References vector< _Tp, _Alloc >::size().
static void createKeys (typename std::vector< key_type >::iterator & intervalIt, const T & dataValue, const Functor & functor, const Functors &... functors) [static]
Use functors on a given value_type object to create a key for every functor.
Parameters:
intervalIt Iterator to a container which will hold the different keys.
dataValue That's the box representing the class we're working on.
functor Functor which provides a std::pair<...> get<size_t>(value_type) member function
functors Other functors which will be used recursively.
See also:
createKeyType()
Definition at line 822 of file fbi.h.
static void createKeys (typename std::vector< key_type >::iterator & intervalIt, const T & dataValue, const Functor & functor) [static]
This is the tail of a recursive call which uses different functors to produce several queries.
Parameters:
intervalIt Iterator to a container which will hold the different keys.
dataValue That's the box representing the class we're working on.
functor Functor which provides a std::pair<...> get<size_t>(value_type) member function
See also:
createKeyType()
Definition at line 801 of file fbi.h.
static std::vector<key_type> getVector (const Container & container, const Functors &... functors) [static]
Calculate the intervals every value_type object is representing and save it as a key_type object to work with.
Parameters:
functors Functors which provide a std::pair<...> get<size_t>(value_type) member function. We create multi-dimensional intervals by using the functor on all indexed dimensions.
container A STL container with value_type objects, has to provide a forward iterator.
See also:
createKeyType()
Definition at line 771 of file fbi.h.
References count(), and SetA< BoxType, TIndices >::static_assert().
The documentation for this class was generated from the following file:
fbi.h