tree: OneWayScanner< PointsContainQueries, Dim > Class Template Reference
OneWayScanner< PointsContainQueries, Dim > Class Template Reference
A scanner to find one type of intersection between two sets of intervals by looking at one of them as a set of points.
Static Public Member Functions
static void scan (const std::vector< const key_type * > &pointsPtrVector, const std::vector< const key_type * > &intervalsPtrVector, State &state, ResultType &resultVector)
Detailed Description
template<typename BoxType, std::size_t... TIndices>
template<bool PointsContainQueries, std::size_t Dim>
class fbi::SetA< BoxType, TIndices >::OneWayScanner< PointsContainQueries, Dim >
A scanner to find one type of intersection between two sets of intervals by looking at one of them as a set of points.
Looking at the one-dimensional problem, two intervals can only overlap if at least one lower endpoint (also called the Head) is contained inside the other interval. We're finding intersections by iterating through the sorted set of points while looking at possible intervals which could contain a given point. The complexity of the problem has, given two sets of size n and m, an upper bound of , for the general case we are looking at .
Note:
As we're only looking at one combination of points/intervals here during one call, only one half of the possible combinations is found, this is why OneWayScanner should always be in pairs.
Template Parameters:
PointsContainQueries As we have to alternate between views, we would like to know which of the two sets at the beginning our points are a subset of. This is needed to calculate the resulting indices by subtracting pointers.
Dim where we should first look for an intersection, all following dimensions will be evaluated via comparisons between two objects.
Definition at line 1414 of file fbi.h.
Member Function Documentation
static void scan (const std::vector< const key_type * > & pointsPtrVector, const std::vector< const key_type * > & intervalsPtrVector, State & state, ResultType & resultVector) [static]
Pass through two sorted vectors and look for matches accordingly.
Parameters:
[in] pointsPtrVector As we're looking at two subsets of intervals, this is the one representing the points.
[in] intervalsPtrVector These are the intervals, for this call.
[in,out] state We need the state (containing 2 pointers) to calculate the correct indices.
[in,out] resultVector Add our results.
Note:
As the OneWayScanner isn't necessarily be called for the last dimension only, we have to use the IntersectionTester to check for intersections in the remaining dimensions.
Definition at line 1428 of file fbi.h.
References vector< _Tp, _Alloc >::begin(), State::calculate(), vector< _Tp, _Alloc >::empty(), vector< _Tp, _Alloc >::end(), and vector< _Tp, _Alloc >::insert().
The documentation for this class was generated from the following file:
fbi.h